# Generated by Django 4.1.7 on 2023-04-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommApp', '0002_alter_products_productdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='productName',
            field=models.CharField(max_length=100),
        ),
    ]
