# Generated by Django 4.2.1 on 2023-05-12 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommApp', '0003_alter_products_productname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='productSubCategory',
            new_name='productBrands',
        ),
    ]
