# Generated by Django 4.2.1 on 2023-05-12 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommApp', '0004_rename_productsubcategory_products_productbrands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='productName',
        ),
    ]
