# Generated by Django 4.2.1 on 2023-06-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommApp', '0007_myorder_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myorder',
            name='Items_Json',
        ),
        migrations.RemoveField(
            model_name='myorder',
            name='user',
        ),
        migrations.AlterField(
            model_name='myorder',
            name='Email',
            field=models.EmailField(max_length=90),
        ),
    ]
