# Generated by Django 4.2.1 on 2023-06-03 19:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eCommApp', '0009_myorder_items_json_myorder_user_alter_myorder_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactUsDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Your_Name', models.CharField(max_length=90)),
                ('Email', models.EmailField(max_length=90)),
                ('Subject', models.CharField(max_length=90)),
                ('Message', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='myOrder',
            new_name='myOrderDb',
        ),
        migrations.RenameModel(
            old_name='products',
            new_name='productsDb',
        ),
    ]
