# Generated by Django 4.2.1 on 2023-06-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommApp', '0011_myprofiledb_rename_your_name_contactusdb_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofiledb',
            name='Gender',
            field=models.CharField(max_length=10),
        ),
    ]
