# Generated by Django 4.2.1 on 2023-06-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommApp', '0012_alter_myprofiledb_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofiledb',
            name='Gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
    ]
