# Generated by Django 4.2.1 on 2023-06-03 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommApp', '0015_alter_myprofiledb_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myProfileDb',
        ),
    ]
