# Generated by Django 4.1.7 on 2023-03-25 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eComAuth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signupDb',
        ),
    ]
